services:
  frontend:
    image: wyj1018/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:80"
    environment:
      - VITE_GRAPHQL_URI=http://3.94.117.55:8082/graphql
      - VITE_SERVER_URI=http://3.94.117.55:8082
    restart: unless-stopped